version: "3"
services: 
    apollo-dev-configservice:
        build: apollo-configservice/
        container_name: apollo-dev-configservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.7
        ports: 
            - 7080:8080
        depends_on:
            - apollo-nginx
        volumes: 
            - /home/mickey/docker/docker-apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp18c5414gvi6244h7o.mysql.rds.aliyuncs.com:3306/ApolloConfigDB_DEV?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=101.37.244.179
            - eureka.instance.hostname=101.37.244.179
            - eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:7080/eureka/
        restart: always

    apollo-dev-adminservice:
        build: apollo-adminservice/
        container_name: apollo-dev-adminservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.3
        depends_on: 
            - apollo-dev-configservice
        ports: 
            - 7090:8090
        volumes: 
            - /home/mickey/docker/docker-apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp18c5414gvi6244h7o.mysql.rds.aliyuncs.com:3306/ApolloConfigDB_DEV?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.23.0.8
            - eureka.instance.hostname=172.23.0.7
            # - eureka.client.serviceUrl.defaultZone: http://${eureka.instance.hostname}:8080/eureka/
        restart: always

networks: 
    docker-apollo-network:
        driver: bridge
        ipam: 
            driver: default
            config: 
            - subnet: 172.23.0.0/24
              gateway: 172.23.0.1
