version: "3"
services: 
    apollo-configservice:
        build: apollo-configservice/
        container_name: apollo-configservice
        ports: 
            - 8080:8080
        volumes: 
            - /Users/wangmeng/workSpace/docker/mickey/apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.0.3:3366/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.19.0.2
            - eureka.instance.hostname=172.19.0.2
        restart: always

    apollo-adminservice:
        build: apollo-adminservice/
        container_name: apollo-adminservice
        depends_on: 
            - apollo-configservice
        ports: 
            - 8090:8090
        volumes: 
            - /Users/wangmeng/workSpace/docker/mickey/apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.0.3:3366/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.19.0.2
            - eureka.instance.hostname=172.19.0.3
        restart: always

    apollo-portal:
        build: apollo-portal/
        container_name: apollo-portal
        depends_on: 
            - apollo-adminservice
        ports: 
            - 8070:8070
        volumes: 
            - /Users/wangmeng/workSpace/docker/mickey/apollo/logs:/opt/logs
            - /Users/wangmeng/workSpace/docker/mickey/apollo/apollo-portal/config/apollo-env.properties:/apollo-portal/config/apollo-env.properties
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://10.0.0.3:3366/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
        restart: always