version: "3"
services: 
    apollo-configservice:
        build: apollo-configservice/
        container_name: apollo-configservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.2
        ports: 
            - 8080:8080
        depends_on:
            - apollo-nginx
        volumes: 
            - /home/mickey/docker/docker-apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp18c5414gvi6244h7o.mysql.rds.aliyuncs.com:3306/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=101.37.244.179
            - eureka.instance.hostname=101.37.244.179
        restart: always

    apollo-adminservice:
        build: apollo-adminservice/
        container_name: apollo-adminservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.3
        depends_on: 
            - apollo-configservice
        ports: 
            - 8090:8090
        volumes: 
            - /home/mickey/docker/docker-apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp18c5414gvi6244h7o.mysql.rds.aliyuncs.com:3306/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.23.0.3
#            - eureka.instance.hostname=172.23.0.2
        restart: always

    apollo-portal:
        build: apollo-portal/
        container_name: apollo-portal
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.4
        depends_on: 
            - apollo-adminservice
        ports: 
            - 8070:8070
        volumes: 
            - /home/mickey/docker/docker-apollo/logs:/opt/logs
            - /home/mickey/docker/docker-apollo/apollo-portal/config/apollo-env.properties:/apollo-portal/config/apollo-env.properties
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://rm-bp18c5414gvi6244h7o.mysql.rds.aliyuncs.com:3306/ApolloPortalDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
        restart: always

    apollo-nginx:
        container_name: apollo-nginx
        image: nginx
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.5
        ports: 
            - 80:80
        volumes: 
            - /home/mickey/docker/docker-apollo/logs/nginx:/var/log/nginx
            - /home/mickey/docker/docker-apollo/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
            - /home/mickey/docker/docker-apollo/nginx/html:/usr/share/nginx/html
        restart: always

networks: 
    docker-apollo-network:
        driver: bridge
        ipam: 
            driver: default
            config: 
            - subnet: 172.23.0.0/24
              gateway: 172.23.0.1
