version: "3"
services: 
    apollo-configservice:
        build: apollo-configservice/
        container_name: apollo-configservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.2
        ports: 
            - 8080:8080
        volumes: 
            - /Users/wangmeng/workSpace/docker/mickey/apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.27.42:3366/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.23.0.2
            - eureka.instance.hostname=192.168.27.42
        restart: always

    apollo-adminservice:
        build: apollo-adminservice/
        container_name: apollo-adminservice
        networks: 
            docker-apollo-network:
                ipv4_address: 172.23.0.3
        depends_on: 
            - apollo-configservice
        ports: 
            - 8090:8090
        volumes: 
            - /Users/wangmeng/workSpace/docker/mickey/apollo/logs:/opt/logs
        environment: 
            - SPRING_DATASOURCE_URL=jdbc:mysql://192.168.27.42:3366/ApolloConfigDB?characterEncoding=utf8
            - SPRING_DATASOURCE_USERNAME=apollo
            - SPRING_DATASOURCE_PASSWORD=2f4a9be476ee499f8e5d8c8f3998cd0a
            - eureka.instance.ip-address=172.23.0.3
            - eureka.instance.hostname=172.23.0.2
        restart: always

networks: 
    docker-apollo-network:
        driver: bridge
        ipam: 
            driver: default
            config: 
            - subnet: 172.23.0.0/24
              gateway: 172.23.0.1
